Add frontend panel file
UtsavSomaiya/website pull request #8
Opened 2022-01-07 05:12 UTC by UtsavSomaiya

In this file,
Using java script, i am creating html elements and add to cart..

2022-01-07 06:14 UTC, gauravmak requested changes

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +        function add_to_cart(id) {
addToCart

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +          if (!add_to_array(cart, id)) {
existsInArray

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +            var index = cart.findIndex((obj => obj.name == document.getElementById('name-' + id).innerHTML));
compare id

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +             return e1.name === document.getElementById('name-' + id).innerHTML;
compare with id

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +             return e1.name === document.getElementById('name-' + id).innerHTML;
what is e1?

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +          //input_value = 1;
?

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +          //input_value = 1;
?

2022-01-07 06:14 UTC, gauravmak commented on index.php
> +        function displayCart(id) {
No need to pass

2022-01-07 06:25 UTC, UtsavSomaiya reviewed
All done

2022-01-07 06:58 UTC, gauravmak requested changes

2022-01-07 06:58 UTC, gauravmak commented on index.php
> +            var div_main = document.createElement('div');
Check variable naming camelcase

2022-01-07 06:58 UTC, gauravmak commented on index.php
> +            var button_1 = document.createElement('button');
??

2022-01-07 10:43 UTC, gauravmak commented on index.php
> +            var div_main = document.createElement('div');
??

2022-01-07 10:43 UTC, gauravmak commented on index.php
> +            var button_1 = document.createElement('button');
What is button_1??

2022-01-07 11:40 UTC, gauravmak requested changes

2022-01-07 11:40 UTC, gauravmak commented on index.php
> +        }
Can we combine these two?

2022-01-08 06:18 UTC, gauravmak requested changes

2022-01-08 06:18 UTC, gauravmak commented on index.php
> +              inputValue = isNaN(inputValue) ? 0 : inputValue;
This line is common right?

2022-01-08 06:18 UTC, gauravmak commented on index.php
> +          function increasingDecreasingQuantity(productId, id, checked) {
changeQuantity

2022-01-08 06:18 UTC, gauravmak commented on index.php
> +            decreaseButton.setAttribute('id','decrease-button-'+id);
is this needed?

2022-01-08 06:18 UTC, gauravmak commented on index.php
> +            decreaseButton.setAttribute('onclick','increasingDecreasingQuantity('+productId+','+id+','+false+')');
How about passing +1 or -1 instead of true or false?

2022-01-08 06:43 UTC, merged